name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - name: Install Bitcoin Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install build-essential cmake pkgconf python3 libevent-dev libboost-dev capnproto libcapnp-dev ccache
      - name: ccache
        uses: actions/cache@v4
        with:
          path: ~/.cache/ccache
          key: ccache-${{ runner.os }}-${{ github.sha }}
          restore-keys: ccache-${{ runner.os }}-
      - name: Checkout Bitcoin Core
        run: |
          git clone --depth 1 https://github.com/bitcoin/bitcoin.git
          # DO NOT MERGE: switch to bitcoin/bitcoin#29409 PR branch
          cd bitcoin
          git fetch --depth 1 origin pull/29409/head:pr-29409
          git checkout pr-29409
      - name: Build Bitcoin Core
        run: |
          cd bitcoin
          cmake -B build -DENABLE_WALLET=ON -DBUILD_TESTS=OFF -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache
          cmake --build build -j $(nproc)
      - name: Run Bitcoin Core Daemon
        run: cd bitcoin && ./build/bin/bitcoin node -chain=regtest -ipcbind=unix -server -debug=ipc -daemon
      - name: Run Test Suite
        env:
          BITCOIN_BIN: ${{ github.workspace }}/bitcoin/build/bin/bitcoin
        run: |
          tests="$(cargo test --test test -- --list | sed -n 's/: test$//p')"
          while IFS= read -r test_name; do
            [ -n "$test_name" ] || continue
            cargo test --test test -- --exact --test-threads=1 "$test_name"
          done <<< "$tests"
